<div id="myCarousel" class="carousel slide">
  <center>
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <a href="https://studio.code.org/projects/gamelab/Sdt_OgR8VajkwZ9t45UeVtzMLGiyqhNFJexB9eCe480" target="_blank">
          <img src="game1.png">
        </a>
        <p>Corrida de carros</p>
      </div>

      <div class="item">
        <a href="https://studio.code.org/projects/gamelab/N25kriFEAiBTZwfbYpDjc_qryNjSBhYW-3fOuYRt_SI" target="_blank">
          <img src="game2.png">
        </a>
          <p>No espaço</p>
        </div>
    
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>

  </center>
  </div>